language: php
php:
  - 5.4
  - 5.5
  - 5.6

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer update

script:
  - ./vendor/bin/codecept run
  - ./vendor/bin/phpcs src
